require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - lib/sample_data.rb
    - test/**/*
    - tmp/**/*
    - vendor/**/*
    - Gemfile
    - Rakefile

# Configured cops
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# https://github.com/rubocop-hq/rubocop/issues/4222
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Metrics/MethodLength:
  Max: 15

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Naming/MethodName:
  Exclude:
    - app/serializers/**/*

Rails/FilePath:
  EnforcedStyle: arguments

Style/SymbolArray:
  EnforcedStyle: brackets

# Disabled cops
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Enabled: false

# Notes
# Rails/SkipsModelValidations: This bot was re-enabled because methods like touch don't work well
# with counter-culture (and other gems that rely on callbacks)
