require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - test/**/*
    - tmp/**/*
    - Gemfile
    - Rakefile

# Configured cops
Naming/MethodName:
  Exclude:
    - app/serializers/**/*

# Disabled cops
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Enabled: false
