require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - test/**/*
    - tmp/**/*
    - vendor/**/*
    - Gemfile
    - Rakefile

# Configured cops
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Naming/MethodName:
  Exclude:
    - app/serializers/**/*

Rails/FilePath:
  EnforcedStyle: arguments

Style/SymbolArray:
  EnforcedStyle: brackets

# Disabled cops
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Enabled: false
