version: '3'

services:
  db:
    image: postgres:13.0
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis:6.0
    volumes:
      - redis:/data

  web:
    depends_on:
      - db
      - redis
    build: .
    command: bin/rails server -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      POSTGRES_URL: postgres://postgres:password@db:5432
      REDIS_URL: redis://redis:6379/0

  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: sidekiq
    volumes:
      - .:/app
    environment:
      POSTGRES_URL: postgres://postgres:password@db:5432
      REDIS_URL: redis://redis:6379/0

volumes:
  redis:
  db:
