version: '3'
services:
  db:
    image: mysql:8.0
    command: [--default-authentication-plugin=mysql_native_password]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  web:
    depends_on:
      - "db"
    build: .
    command: bin/rails server -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/app
