apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ripplr-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: services@ripplr.io
    privateKeySecretRef:
      name: ripplr-letsencrypt-key
    solvers:
    - http01:
        ingress:
          class: nginx
