default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV['POSTGRES_URL'] + '/ripplr_development' %>

test:
  <<: *default
  url: <%= ENV['POSTGRES_URL'] + '/ripplr_test' %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
