default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: db

development:
  <<: *default
  database: ripplr_api_development

test:
  <<: *default
  database: ripplr_api_test

production:
  <<: *default
  database: ripplr_api_production
