:queues:
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge
  - metrics
  - alerts

:schedule:
  content_sources_scheduler:
    cron: '0 */10 * * * *'   # Every 10 minutes at 00 seconds
    class: ContentSources::ScheduleWorker

  hourly_inbox_notifications:
    cron: '0 0 * * * *'   # Every hour at 00 minutes, 00 seconds
    class: InboxNotifications::DeliverManagerHourlyWorker
