:queues:
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge
  - metrics
  - alerts

:schedule:
  # hourly_push_notifications:
  #   cron: '0 0 * * * *'   # Every hour at 00 minutes, 00 seconds
  #   class: PushNotifications::HourlyDeliverWorker

  hourly_inbox_notifications:
    cron: '0 0 * * * *'   # Every hour at 00 minutes, 00 seconds
    class: InboxNotifications::DeliverManagerHourlyWorker
