:queues:
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge
  - metrics

:schedule:
  hourly_push_notifications:
    cron: '* 0 * * * *'   # Every hour at 00 minutes
    class: PushNotifications::HourlyDeliverWorker
