apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: registry.digitalocean.com/ripplr/ripplr-api:latest
        command: ["bin/rails"]
        args: ["db:migrate"]
        envFrom:
        - configMapRef:
            name: ripplr-config
        env:
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: ripplr-secrets
              key: rails_master_key
