apiVersion: apps/v1
kind: Deployment
metadata:
  name: ripplr-api
spec:
  replicas: 2
  minReadySeconds: 5
  progressDeadlineSeconds: 30
  selector:
    matchLabels:
      app: ripplr-api
  template:
    metadata:
      labels:
        app: ripplr-api
    spec:
      containers:
      - name: ripplr-api
        image: registry.digitalocean.com/ripplr/ripplr-api:latest
        command: ["bin/rails"]
        args: ["server", "-b", "0.0.0.0"]
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: ripplr-config
        env:
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: ripplr-secrets
              key: rails_master_key
