apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq
spec:
  replicas: 2
  progressDeadlineSeconds: 180
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
      - name: sidekiq
        image: registry.digitalocean.com/ripplr/ripplr-api:latest
        command: ["sidekiq"]
        envFrom:
        - configMapRef:
            name: ripplr-config
        env:
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: ripplr-secrets
              key: rails_master_key
