name: Deploy

on:
  push:
    branches: [ master ]

env:
  IMAGE_URL: registry.digitalocean.com/ripplr/ripplr-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ripplr

      - name: Build image
        run: docker build . -t ${IMAGE_URL}:${GITHUB_SHA:0:8} -t ${IMAGE_URL}:latest

      - name: Upload image to registry
        run: |
          doctl registry login
          docker push IMAGE_URL

      - name: Run migrations
        run: echo TODO

