name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ripplr

      - name: Save image names
        run: |
          IMAGE_NAME=ripplr/ripplr-api
          SHA8=$( echo ${GITHUB_SHA} | head -c8 )
          TAGGED_IMAGE=$( echo ${IMAGE_NAME}:${SHA8} )
          LATEST_IMAGE=$( echo ${IMAGE_NAME}:latest )

      - name: Build image
        run: docker build --tag ${TAGGED_IMAGE} .

      - name: Upload image to registry
        run: |
          doctl registry login
          docker tag ${TAGGED_IMAGE} registry.digitalocean.com/${TAGGED_IMAGE}
          docker push registry.digitalocean.com/${TAGGED_IMAGE}
