name: Deploy

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: ripplr/ripplr-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ripplr

      - name: Build image
        run: docker build --tag ${IMAGE_NAME}:${GITHUB_SHA:0:7} .

      - name: Upload image to registry
        run: |
          doctl registry login
          docker tag ${IMAGE_NAME}:${GITHUB_SHA:0:7} registry.digitalocean.com/${IMAGE_NAME}:${GITHUB_SHA:0:7}
          docker push registry.digitalocean.com/${IMAGE_NAME}:${GITHUB_SHA:0:7}
