name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ripplr/ripplr-api
      SHA8: ${GITHUB_SHA::8}
      TAGGED_IMAGE: ${{ env.IMAGE_NAME }}:${{ env.SHA8 }}
      LATEST_IMAGE: ${{ env.IMAGE_NAME }}:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ripplr

      - name: Build image
        run: docker build --tag ${{ env.TAGGED_IMAGE }} .

      - name: Upload image to registry
        run: |
          doctl registry login
          docker tag ${{ env.TAGGED_IMAGE }} registry.digitalocean.com/${{ env.TAGGED_IMAGE }}
          docker push registry.digitalocean.com/${{ env.TAGGED_IMAGE }}
