name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  upload_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build image
        run: docker build . --file Dockerfile --tag ripplr-api
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Upload image to registry
        run: |
          doctl registry login
          docker tag ripplr-api registry.digitalocean.com/ripplr/ripplr-api
          docker push registry.digitalocean.com/ripplr/ripplr-api
