name: Generate Database Schema

on: [ pull_request ]

jobs:
  run:
    name: Generate DB Schema with rails-erb
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1

      - name: Install graphviz dependency
        run: sudo apt-get install -y graphviz

      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle install
        run: bundle check || bundle install --path vendor/bundle --jobs 4 --retry 3

      - name: Generate Schema
        run: bundle exec erd

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Generating DB Schema'
          add: 'docs/erd.pdf'
