name: Linters
on: [pull_request]

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-rubocop@v1
        with:
          rubocop_extensions: rubocop-rails
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
