name: Ruby Tests
on: [push,pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: gimenete/rubocop-action@1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
